[project]
name = "agent-sandbox-hello-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "k8s-agent-sandbox>=1.0.2",
    "langchain>=1.4.0",
    "langchain-mcp-adapters>=0.3.2",
    "langchain-ollama>=1.1.0",
    "langfuse>=4.15.2",
    "langgraph>=1.2.11",
    "python-dotenv==1.2.3",
]
